// Continent mapping for country codes to continents
export const CONTINENTS = {
  AFRICA: 'Africa',
  ASIA: 'Asia',
  EUROPE: 'Europe',
  NORTH_AMERICA: 'North America',
  SOUTH_AMERICA: 'South America',
  OCEANIA: 'Oceania',
  ANTARCTICA: 'Antarctica'
} as const;

export type Continent = typeof CONTINENTS[keyof typeof CONTINENTS];

// Country code to continent mapping (ISO2 codes)
export const COUNTRY_TO_CONTINENT: Record<string, Continent> = {
  // Africa
  'AO': CONTINENTS.AFRICA, 'BF': CONTINENTS.AFRICA, 'BI': CONTINENTS.AFRICA, 'BJ': CONTINENTS.AFRICA,
  'BW': CONTINENTS.AFRICA, 'CD': CONTINENTS.AFRICA, 'CF': CONTINENTS.AFRICA, 'CG': CONTINENTS.AFRICA,
  'CI': CONTINENTS.AFRICA, 'CM': CONTINENTS.AFRICA, 'CV': CONTINENTS.AFRICA, 'DJ': CONTINENTS.AFRICA,
  'DZ': CONTINENTS.AFRICA, 'EG': CONTINENTS.AFRICA, 'EH': CONTINENTS.AFRICA, 'ER': CONTINENTS.AFRICA,
  'ET': CONTINENTS.AFRICA, 'GA': CONTINENTS.AFRICA, 'GH': CONTINENTS.AFRICA, 'GM': CONTINENTS.AFRICA,
  'GN': CONTINENTS.AFRICA, 'GQ': CONTINENTS.AFRICA, 'GW': CONTINENTS.AFRICA, 'KE': CONTINENTS.AFRICA,
  'KM': CONTINENTS.AFRICA, 'LR': CONTINENTS.AFRICA, 'LS': CONTINENTS.AFRICA, 'LY': CONTINENTS.AFRICA,
  'MA': CONTINENTS.AFRICA, 'MG': CONTINENTS.AFRICA, 'ML': CONTINENTS.AFRICA, 'MR': CONTINENTS.AFRICA,
  'MU': CONTINENTS.AFRICA, 'MW': CONTINENTS.AFRICA, 'MZ': CONTINENTS.AFRICA, 'NA': CONTINENTS.AFRICA,
  'NE': CONTINENTS.AFRICA, 'NG': CONTINENTS.AFRICA, 'RE': CONTINENTS.AFRICA, 'RW': CONTINENTS.AFRICA,
  'SC': CONTINENTS.AFRICA, 'SD': CONTINENTS.AFRICA, 'SH': CONTINENTS.AFRICA, 'SL': CONTINENTS.AFRICA,
  'SN': CONTINENTS.AFRICA, 'SO': CONTINENTS.AFRICA, 'SS': CONTINENTS.AFRICA, 'ST': CONTINENTS.AFRICA,
  'SZ': CONTINENTS.AFRICA, 'TD': CONTINENTS.AFRICA, 'TG': CONTINENTS.AFRICA, 'TN': CONTINENTS.AFRICA,
  'TZ': CONTINENTS.AFRICA, 'UG': CONTINENTS.AFRICA, 'YT': CONTINENTS.AFRICA, 'ZA': CONTINENTS.AFRICA,
  'ZM': CONTINENTS.AFRICA, 'ZW': CONTINENTS.AFRICA,

  // Asia
  'AE': CONTINENTS.ASIA, 'AF': CONTINENTS.ASIA, 'AM': CONTINENTS.ASIA, 'AZ': CONTINENTS.ASIA,
  'BD': CONTINENTS.ASIA, 'BH': CONTINENTS.ASIA, 'BN': CONTINENTS.ASIA, 'BT': CONTINENTS.ASIA,
  'CN': CONTINENTS.ASIA, 'CY': CONTINENTS.ASIA, 'GE': CONTINENTS.ASIA, 'HK': CONTINENTS.ASIA,
  'ID': CONTINENTS.ASIA, 'IL': CONTINENTS.ASIA, 'IN': CONTINENTS.ASIA, 'IQ': CONTINENTS.ASIA,
  'IR': CONTINENTS.ASIA, 'JO': CONTINENTS.ASIA, 'JP': CONTINENTS.ASIA, 'KG': CONTINENTS.ASIA,
  'KH': CONTINENTS.ASIA, 'KP': CONTINENTS.ASIA, 'KR': CONTINENTS.ASIA, 'KW': CONTINENTS.ASIA,
  'KZ': CONTINENTS.ASIA, 'LA': CONTINENTS.ASIA, 'LB': CONTINENTS.ASIA, 'LK': CONTINENTS.ASIA,
  'MM': CONTINENTS.ASIA, 'MN': CONTINENTS.ASIA, 'MO': CONTINENTS.ASIA, 'MV': CONTINENTS.ASIA,
  'MY': CONTINENTS.ASIA, 'NP': CONTINENTS.ASIA, 'OM': CONTINENTS.ASIA, 'PH': CONTINENTS.ASIA,
  'PK': CONTINENTS.ASIA, 'PS': CONTINENTS.ASIA, 'QA': CONTINENTS.ASIA, 'SA': CONTINENTS.ASIA,
  'SG': CONTINENTS.ASIA, 'SY': CONTINENTS.ASIA, 'TH': CONTINENTS.ASIA, 'TJ': CONTINENTS.ASIA,
  'TM': CONTINENTS.ASIA, 'TR': CONTINENTS.ASIA, 'TW': CONTINENTS.ASIA, 'UZ': CONTINENTS.ASIA,
  'VN': CONTINENTS.ASIA, 'YE': CONTINENTS.ASIA,

  // Europe
  'AD': CONTINENTS.EUROPE, 'AL': CONTINENTS.EUROPE, 'AT': CONTINENTS.EUROPE, 'BA': CONTINENTS.EUROPE,
  'BE': CONTINENTS.EUROPE, 'BG': CONTINENTS.EUROPE, 'BY': CONTINENTS.EUROPE, 'CH': CONTINENTS.EUROPE,
  'CZ': CONTINENTS.EUROPE, 'DE': CONTINENTS.EUROPE, 'DK': CONTINENTS.EUROPE, 'EE': CONTINENTS.EUROPE,
  'ES': CONTINENTS.EUROPE, 'FI': CONTINENTS.EUROPE, 'FO': CONTINENTS.EUROPE, 'FR': CONTINENTS.EUROPE,
  'GB': CONTINENTS.EUROPE, 'GG': CONTINENTS.EUROPE, 'GI': CONTINENTS.EUROPE, 'GR': CONTINENTS.EUROPE,
  'HR': CONTINENTS.EUROPE, 'HU': CONTINENTS.EUROPE, 'IE': CONTINENTS.EUROPE, 'IM': CONTINENTS.EUROPE,
  'IS': CONTINENTS.EUROPE, 'IT': CONTINENTS.EUROPE, 'JE': CONTINENTS.EUROPE, 'LI': CONTINENTS.EUROPE,
  'LT': CONTINENTS.EUROPE, 'LU': CONTINENTS.EUROPE, 'LV': CONTINENTS.EUROPE, 'MC': CONTINENTS.EUROPE,
  'MD': CONTINENTS.EUROPE, 'ME': CONTINENTS.EUROPE, 'MK': CONTINENTS.EUROPE, 'MT': CONTINENTS.EUROPE,
  'NL': CONTINENTS.EUROPE, 'NO': CONTINENTS.EUROPE, 'PL': CONTINENTS.EUROPE, 'PT': CONTINENTS.EUROPE,
  'RO': CONTINENTS.EUROPE, 'RS': CONTINENTS.EUROPE, 'RU': CONTINENTS.EUROPE, 'SE': CONTINENTS.EUROPE,
  'SI': CONTINENTS.EUROPE, 'SJ': CONTINENTS.EUROPE, 'SK': CONTINENTS.EUROPE, 'SM': CONTINENTS.EUROPE,
  'UA': CONTINENTS.EUROPE, 'VA': CONTINENTS.EUROPE, 'XK': CONTINENTS.EUROPE,

  // North America
  'AG': CONTINENTS.NORTH_AMERICA, 'AI': CONTINENTS.NORTH_AMERICA, 'AW': CONTINENTS.NORTH_AMERICA,
  'BB': CONTINENTS.NORTH_AMERICA, 'BL': CONTINENTS.NORTH_AMERICA, 'BM': CONTINENTS.NORTH_AMERICA,
  'BQ': CONTINENTS.NORTH_AMERICA, 'BS': CONTINENTS.NORTH_AMERICA, 'BZ': CONTINENTS.NORTH_AMERICA,
  'CA': CONTINENTS.NORTH_AMERICA, 'CR': CONTINENTS.NORTH_AMERICA, 'CU': CONTINENTS.NORTH_AMERICA,
  'CW': CONTINENTS.NORTH_AMERICA, 'DM': CONTINENTS.NORTH_AMERICA, 'DO': CONTINENTS.NORTH_AMERICA,
  'GD': CONTINENTS.NORTH_AMERICA, 'GL': CONTINENTS.NORTH_AMERICA, 'GP': CONTINENTS.NORTH_AMERICA,
  'GT': CONTINENTS.NORTH_AMERICA, 'HN': CONTINENTS.NORTH_AMERICA, 'HT': CONTINENTS.NORTH_AMERICA,
  'JM': CONTINENTS.NORTH_AMERICA, 'KN': CONTINENTS.NORTH_AMERICA, 'KY': CONTINENTS.NORTH_AMERICA,
  'LC': CONTINENTS.NORTH_AMERICA, 'MF': CONTINENTS.NORTH_AMERICA, 'MQ': CONTINENTS.NORTH_AMERICA,
  'MS': CONTINENTS.NORTH_AMERICA, 'MX': CONTINENTS.NORTH_AMERICA, 'NI': CONTINENTS.NORTH_AMERICA,
  'PA': CONTINENTS.NORTH_AMERICA, 'PM': CONTINENTS.NORTH_AMERICA, 'PR': CONTINENTS.NORTH_AMERICA,
  'SV': CONTINENTS.NORTH_AMERICA, 'SX': CONTINENTS.NORTH_AMERICA, 'TC': CONTINENTS.NORTH_AMERICA,
  'TT': CONTINENTS.NORTH_AMERICA, 'US': CONTINENTS.NORTH_AMERICA, 'VC': CONTINENTS.NORTH_AMERICA,
  'VG': CONTINENTS.NORTH_AMERICA, 'VI': CONTINENTS.NORTH_AMERICA,

  // South America
  'AR': CONTINENTS.SOUTH_AMERICA, 'BO': CONTINENTS.SOUTH_AMERICA, 'BR': CONTINENTS.SOUTH_AMERICA,
  'CL': CONTINENTS.SOUTH_AMERICA, 'CO': CONTINENTS.SOUTH_AMERICA, 'EC': CONTINENTS.SOUTH_AMERICA,
  'FK': CONTINENTS.SOUTH_AMERICA, 'GF': CONTINENTS.SOUTH_AMERICA, 'GY': CONTINENTS.SOUTH_AMERICA,
  'PE': CONTINENTS.SOUTH_AMERICA, 'PY': CONTINENTS.SOUTH_AMERICA, 'SR': CONTINENTS.SOUTH_AMERICA,
  'UY': CONTINENTS.SOUTH_AMERICA, 'VE': CONTINENTS.SOUTH_AMERICA,

  // Oceania
  'AS': CONTINENTS.OCEANIA, 'AU': CONTINENTS.OCEANIA, 'CK': CONTINENTS.OCEANIA, 'FJ': CONTINENTS.OCEANIA,
  'FM': CONTINENTS.OCEANIA, 'GU': CONTINENTS.OCEANIA, 'KI': CONTINENTS.OCEANIA, 'MH': CONTINENTS.OCEANIA,
  'MP': CONTINENTS.OCEANIA, 'NC': CONTINENTS.OCEANIA, 'NF': CONTINENTS.OCEANIA, 'NR': CONTINENTS.OCEANIA,
  'NU': CONTINENTS.OCEANIA, 'NZ': CONTINENTS.OCEANIA, 'PF': CONTINENTS.OCEANIA, 'PG': CONTINENTS.OCEANIA,
  'PN': CONTINENTS.OCEANIA, 'PW': CONTINENTS.OCEANIA, 'SB': CONTINENTS.OCEANIA, 'TK': CONTINENTS.OCEANIA,
  'TL': CONTINENTS.OCEANIA, 'TO': CONTINENTS.OCEANIA, 'TV': CONTINENTS.OCEANIA, 'UM': CONTINENTS.OCEANIA,
  'VU': CONTINENTS.OCEANIA, 'WF': CONTINENTS.OCEANIA, 'WS': CONTINENTS.OCEANIA,

  // Antarctica
  'AQ': CONTINENTS.ANTARCTICA
};

export function getContinentFromCountryCode(countryCode: string | undefined): Continent | null {
  if (!countryCode) return null;
  return COUNTRY_TO_CONTINENT[countryCode.toUpperCase()] || null;
}

export function getAllContinents(): Continent[] {
  return Object.values(CONTINENTS);
}
